services:
  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  deploy-af-two:
    image: localhost:5000/deploy-af-two:latest
    pull_policy: always
    restart: always
    env_file:
      - .env.live
    volumes:
      - deploy-af-two-db:/code/db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy-af-two.rule=PathPrefix(`/`)"
      - "traefik.http.services.deploy-af-two.loadbalancer.server.port=3500"
      - "traefik.http.routers.deploy-af-two.priority=2"

volumes:
  deploy-af-two-db: